[package]
name = "fido-authenticator"
version = "0.1.1"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/solokeys/fido-authenticator"
documentation = "https://docs.rs/fido-authenticator"
description = "FIDO authenticator Trussed app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "usbip"
required-features = ["dispatch"]

[dependencies]
ctap-types = { version = "0.3.1", features = ["get-info-full", "large-blobs", "third-party-payment"] }
cosey = "0.3"
delog = "0.1.0"
heapless = "0.7"
littlefs2-core = "0.1"
serde = { version = "1.0", default-features = false }
serde_bytes = { version = "0.11.14", default-features = false }
serde-indexed = "0.1.0"
sha2 = { version = "0.10", default-features = false }
trussed = "0.1"
trussed-fs-info = "0.1.0"
trussed-hkdf = { version = "0.2.0" }
trussed-chunked = { version = "0.1.0", optional = true }

apdu-app = { version = "0.1", optional = true }
ctaphid-dispatch = { version = "0.1", optional = true }
iso7816 = { version = "0.1.2", optional = true }

# This dependency is used indirectly via Trussed.  We only want to make sure that we use at least
# 0.4.1 so that the persistent state is deserialized correctly.
cbor-smol = { version = ">= 0.4.1" }

[features]
dispatch = ["apdu-dispatch", "ctaphid-dispatch", "iso7816"]
apdu-dispatch = ["dep:apdu-app"]
disable-reset-time-window = []

# enables support for a large-blob array longer than 1024 bytes
chunked = ["trussed-chunked"]

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []

[dev-dependencies]
aes = "0.8.4"
cbc = { version = "0.1.2", features = ["alloc"] }
ciborium = { version = "0.2.2" }
ciborium-io = "0.2.2"
cipher = "0.4.4"
ctaphid = { version = "0.3.1", default-features = false }
delog = { version = "0.1.6", features = ["std-log"] }
env_logger = "0.11.0"
hex-literal = "0.4.1"
hmac = "0.12.1"
interchange = "0.3.0"
littlefs2 = "0.5.0"
log = "0.4.21"
p256 = { version = "0.13.2", features = ["ecdh"] }
rand = "0.8.4"
sha2 = "0.10"
serde_test = "1.0.176"
trussed = { version = "0.1", features = ["virt"] }
trussed-staging = { version = "0.3.0", features = ["chunked", "hkdf", "virt", "fs-info"] }
trussed-usbip = { version = "0.0.1", default-features = false, features = ["ctaphid"] }
usbd-ctaphid = "0.1.0"
x509-parser = "0.16.0"

[package.metadata.docs.rs]
features = ["dispatch"]

[patch.crates-io]
ctaphid-dispatch = { git = "https://github.com/trussed-dev/ctaphid-dispatch.git", rev = "57cb3317878a8593847595319aa03ef17c29ec5b" }
trussed = { git = "https://github.com/trussed-dev/trussed.git", rev = "046478b7a4f6e2315acf9112d98308379c2e3eee" }
trussed-chunked = { git = "https://github.com/trussed-dev/trussed-staging.git", tag = "chunked-v0.1.0" }
trussed-fs-info = { git = "https://github.com/trussed-dev/trussed-staging.git", rev = "fs-info-v0.1.0" }
trussed-hkdf = { git = "https://github.com/trussed-dev/trussed-staging.git", tag = "hkdf-v0.2.0" }
trussed-staging = { git = "https://github.com/trussed-dev/trussed-staging.git", rev = "53eba84d2cd0bcacc3a7096d4b7a2490dcf6f069" }
trussed-usbip = { git = "https://github.com/Nitrokey/pc-usbip-runner.git", tag = "v0.0.1-nitrokey.5" }
usbd-ctaphid = { git = "https://github.com/trussed-dev/usbd-ctaphid.git", rev = "dcff9009c3cd1ef9e5b09f8f307aca998fc9a8c8" }
